apiVersion: v1
kind: Service
metadata:
  labels:
    app: reservatons
  name: reservatons
spec:
  ports:
  - name: "http"
    port: 3004
    protocol: TCP
    targetPort: 3004
  selector:
    app: reservatons
  type: NodePort
